Release 2.1.0
eastgenomics/eggd_generate_workbook pull request #110
Opened 2022-07-01 16:37 UTC by jethror1

## Summary

All changes covered by previously reviewed PRs -> release-2.1.0 branch

## Changes
- Fix for handling gCNV VCFs due to no reference stored in header
  - PR: https://github.com/eastgenomics/eggd_generate_workbook/pull/86
  - Fixes #84 
- Update readme
  - PR: https://github.com/eastgenomics/eggd_generate_workbook/pull/85
- Freeze header row on scrolling for variant sheets
  - PR: https://github.com/eastgenomics/eggd_generate_workbook/pull/101
  - Fixes #99 
- Fix colouring for BA1 in ACMG sheet
  - PR: https://github.com/eastgenomics/eggd_generate_workbook/pull/87
  - Fixes #90 
- Tweak column widths
  - PR: https://github.com/eastgenomics/eggd_generate_workbook/pull/102
  - Fixes #88 
  - Fixes #89 
- Fix bug in filtering for variants with previously applied filters
  - PR: https://github.com/eastgenomics/eggd_generate_workbook/pull/106
  - Fixes: #104 

```
$ python3 -m pytest -v resources/home/dnanexus/generate_workbook/tests/
======================================================== test session starts =========================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_vcf2xls_nirvana/resources/home/dnanexus/generate_workbook/tests, configfile: pytest.ini
collected 27 items                                                                                                                   

resources/home/dnanexus/generate_workbook/tests/test_columns.py::test PASSED                                                   [  3%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestMainColumns::test_chrom PASSED                            [  7%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestMainColumns::test_pos PASSED                              [ 11%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestMainColumns::test_id PASSED                               [ 14%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestMainColumns::test_ref PASSED                              [ 18%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestMainColumns::test_alt PASSED                              [ 22%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestMainColumns::test_qual PASSED                             [ 25%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestMainColumns::test_filter PASSED                           [ 29%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestInfoColumn::test_parsed_correct_columns_from_info_records PASSED [ 33%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestInfoColumn::test_parsed_correct_gnomAD_AF_values PASSED   [ 37%]
resources/home/dnanexus/generate_workbook/tests/test_columns.py::TestFormatSample::test_format_sample_values_are_correct PASSED [ 40%]
resources/home/dnanexus/generate_workbook/tests/test_filters.py::TestModifyingFieldTypes::test_type_correctly_modified PASSED  [ 44%]
resources/home/dnanexus/generate_workbook/tests/test_filters.py::TestModifyingFieldTypes::test_header_overwritten_correctly PASSED [ 48%]
resources/home/dnanexus/generate_workbook/tests/test_filters.py::TestFilters::test_filter_with_include_eq PASSED               [ 51%]
resources/home/dnanexus/generate_workbook/tests/test_filters.py::TestFilters::test_filter_with_exclude_eq PASSED               [ 55%]
resources/home/dnanexus/generate_workbook/tests/test_filters.py::TestFilters::test_filter_with_exclude_gt PASSED               [ 59%]
resources/home/dnanexus/generate_workbook/tests/test_filters.py::TestFilters::test_combined_exclude_float_and_string PASSED    [ 62%]
resources/home/dnanexus/generate_workbook/tests/test_filters.py::TestFilters::test_combined_filter_and_recover PASSED          [ 66%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py::TestHeader::test_column_names PASSED                              [ 70%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py::TestHeader::test_parse_reference PASSED                           [ 74%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py::TestHeader::test_only_header_parsed PASSED                        [ 77%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py::TestDataFrameActions::test_drop_columns_exclude PASSED            [ 81%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py::TestDataFrameActions::test_drop_columns_include PASSED            [ 85%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py::TestDataFrameActions::test_reorder_columns_correct_order PASSED   [ 88%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py::TestDataFrameActions::test_reorder_columns_no_dropped_columns PASSED [ 92%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py::TestDataFrameActions::test_non_rename_columns_unaffacted PASSED   [ 96%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py::TestDataFrameActions::test_renamed_correctly PASSED               [100%]
```

2022-07-01 16:37 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/generate_workbook/tests/test_columns.py`](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/resources/home/dnanexus/generate_workbook/tests/test_columns.py):

> [Line 178:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/resources/home/dnanexus/generate_workbook/tests/test_columns.py#L178): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 187:34](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/resources/home/dnanexus/generate_workbook/tests/test_columns.py#L187): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\.'
> [Line 187:37](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/resources/home/dnanexus/generate_workbook/tests/test_columns.py#L187): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\-'
> [Line 198:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/resources/home/dnanexus/generate_workbook/tests/test_columns.py#L198): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)





* In the file [`resources/home/dnanexus/generate_workbook/utils/vcf.py`](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/resources/home/dnanexus/generate_workbook/utils/vcf.py):

> [Line 44:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/resources/home/dnanexus/generate_workbook/utils/vcf.py#L44): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 45:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/resources/home/dnanexus/generate_workbook/utils/vcf.py#L45): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)

2022-07-05 16:12 UTC, woook requested changes
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/110)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @oniblock)

___
*[`Readme.md` line 110 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/110#-N6E7A6TCUFoWOYvwUlH:-N6E7A6TCUFoWOYvwUlI:bb6xb9l) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/Readme.md#L110)):*
> ```Markdown
> Please be aware of the difference between using `-i / --include` and `-e / --exclude`, as they may not filter the same (i.e. including under 2% (`-i 'gnomAD_AF<0.02'`) != excluding over 2% (`-e gnomAD_AF>0.02`)). In this case, missing values (represented in the vcf with a `'.'`) will be filtered **out** with `--include` as they will not meet the filter. If they should be retained, `--exclude` should be used.
> 
> If running the filtering with any operator containing `!` (i.e. `CSQ_ClinVar_CLNSIG!~ \"pathogenic\/i\"`) via an interactive shell, the `set +H` first first be set to stop shell history substitution, see the GNU set builtin [documentation][set-docs] for details.
> ```

Huh?



_Code quote:_
```Markdown
the `set +H` first first be set
```


<!-- Sent from Reviewable.io -->

2022-07-05 16:17 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/110)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @oniblock and @woook)

___
*[`Readme.md` line 110 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/110#-N6E7A6TCUFoWOYvwUlH:-N6E8V6e0JG84TztUkmb:byfucuf) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/668c5c6022ff3765dc4330ae3c035dd74bab1e64/Readme.md#L110)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Huh?
</blockquote></details>

I clearly can't form correct sentences, updated it


<!-- Sent from Reviewable.io -->

2022-07-05 16:18 UTC, woook approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oniblock)



<!-- Sent from Reviewable.io -->

2022-07-05 16:18 UTC, merged