Minor changes and bug fixes
eastgenomics/eggd_generate_workbook pull request #66
Opened 2022-04-07 11:54 UTC by jethror1

- fix bug in not adding sample name to exclude sheet when `--add_samplename_column` specified
- fix uploading intermediate vcfs from app with `-keep_tmp`
- updates to readme
- add method to verify no variants dropped after filtering and intersecting
- minor improvements to app code and formatting
- correctly handle adding panel and clinical indication strings to summary sheet for dias

2022-04-07 16:16 UTC, pep8speaks commented
Hello @jethror1! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/generate_workbook/generate_workbook.py`](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/generate_workbook.py):

> [Line 49:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/generate_workbook.py#L49): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)



* In the file [`resources/home/dnanexus/generate_workbook/utils/filters.py`](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/utils/filters.py):

> [Line 147:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/utils/filters.py#L147): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`resources/home/dnanexus/generate_workbook/utils/vcf.py`](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/utils/vcf.py):

> [Line 52:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/utils/vcf.py#L52): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 53:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/utils/vcf.py#L53): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 106:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/utils/vcf.py#L106): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 591:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/utils/vcf.py#L591): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 609:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/ff84986a713afb4fe141e92d8079e3c91f7e5fcc/resources/home/dnanexus/generate_workbook/utils/vcf.py#L609): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2022-04-07 21:28 UTC, mattgarner requested changes
> Reviewed 1 of 6 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/66)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[Readme.md, line 42 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/66#-N-4rgIE6gzFmj2zPK9j:-N-4rgIE6gzFmj2zPK9k:b-1uy8mp) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/2ecffdd83e26736c1cbe847c2119f5877ce67609/Readme.md#L42)):*
> ```Markdown
> `--keep_tmp` (`bool`): Determines if to upload the intermediate bcftools split and filtered vcfs. `*.split.vcf.gz` is the output from `bcftools split-vep` and `*.filter.vcf.gz` is the output from `bcftools filter`.
> 
> `--keep_filtered` (`bool`): Determines if filtered rows from `--filter` are retained in a seperate 'filtered' tab (default: `True`).
> ```

excluded



_Code quote:_
```Markdown
filtered
```
___
*[Readme.md, line 55 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/66#-N-4sHuX7VAR87_T2sdB:-N-4sHuX7VAR87_T2sdC:bvydx6e) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/2ecffdd83e26736c1cbe847c2119f5877ce67609/Readme.md#L55)):*
> ```Markdown
> 
> `--panel` (`string`): Name of panel to display in summary sheet.
> ```

--clinical-indication

seems to be missing
___
*[Readme.md, line 79 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/66#-N-4sd7eCEQT0KTP4cYs:-N-4sd7f4cNYm-phBCr3:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/2ecffdd83e26736c1cbe847c2119f5877ce67609/Readme.md#L79)):*
> ```Markdown
> - rename the gnomAD genomes AF column
> - add the summary sheet for Dias
> - exlcude the `MLEAF`, `MGRankSum` and `MLEAC` columns from the output
> ```

typo



_Code quote:_
```Markdown
exlcude
```


<!-- Sent from Reviewable.io -->

2022-04-07 23:08 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/66)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[Readme.md, line 42 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/66#-N-4rgIE6gzFmj2zPK9j:-N-5GrxF4qyYAShINCs1:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/2ecffdd83e26736c1cbe847c2119f5877ce67609/Readme.md#L42)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

excluded
</blockquote></details>

Done.
___
*[Readme.md, line 55 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/66#-N-4sHuX7VAR87_T2sdB:-N-5H1iJ6C-OGVH4oBQQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/2ecffdd83e26736c1cbe847c2119f5877ce67609/Readme.md#L55)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

--clinical-indication

seems to be missing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-08 11:55 UTC, mattgarner approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-04-08 11:55 UTC, merged