Fix for correctly retrieving filtered out variants, update unit tests
eastgenomics/eggd_generate_workbook pull request #68
Opened 2022-04-21 21:29 UTC by jethror1

- Adds fix for bug in bcftools isec returning wrong variant for those excluded
  - switch to using `bcftools filter` with `--soft-filter` to tag the variants to exclude, then read these into a dataframe and split on the tag
  - changes in `vcf.py` to accommodate new filtering
- updated and fixed unit tests:

```
jethro@jethro-T490:~/Projects/eggd_vcf2xls_nirvana/resources/home/dnanexus/generate_workbook/tests$ python3 -m pytest -v .
================================================================================================================================= test session starts =================================================================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_vcf2xls_nirvana/resources/home/dnanexus/generate_workbook/tests
collected 18 items                                                                                                                                                                                                                                                                    

test_columns.py::TestInfoColumn::test_parsed_correct_columns_from_info_records PASSED                                                                                                                                                                                           [  5%]
test_columns.py::TestInfoColumn::test_parsed_correct_gnomAD_AF_values PASSED                                                                                                                                                                                                    [ 11%]
test_columns.py::TestFormatSample::test_format_sample_values_are_correct PASSED                                                                                                                                                                                                 [ 16%]
test_filters.py::TestModifyingFieldTypes::test_type_correctly_modified PASSED                                                                                                                                                                                                   [ 22%]
test_filters.py::TestModifyingFieldTypes::test_header_overwritten_correctly PASSED                                                                                                                                                                                              [ 27%]
test_filters.py::TestFilters::test_filter_with_include_eq PASSED                                                                                                                                                                                                                [ 33%]
test_filters.py::TestFilters::test_filter_with_exclude_eq PASSED                                                                                                                                                                                                                [ 38%]
test_filters.py::TestFilters::test_filter_with_exclude_gt PASSED                                                                                                                                                                                                                [ 44%]
test_filters.py::TestFilters::test_combined_exclude_float_and_string PASSED                                                                                                                                                                                                     [ 50%]
test_vcf.py::TestHeader::test_column_names PASSED                                                                                                                                                                                                                               [ 55%]
test_vcf.py::TestHeader::test_parse_reference PASSED                                                                                                                                                                                                                            [ 61%]
test_vcf.py::TestHeader::test_only_header_parsed PASSED                                                                                                                                                                                                                         [ 66%]
test_vcf.py::TestDataFrameActions::test_drop_columns_exclude PASSED                                                                                                                                                                                                             [ 72%]
test_vcf.py::TestDataFrameActions::test_drop_columns_include PASSED                                                                                                                                                                                                             [ 77%]
test_vcf.py::TestDataFrameActions::test_reorder_columns_correct_order PASSED                                                                                                                                                                                                    [ 83%]
test_vcf.py::TestDataFrameActions::test_reorder_columns_no_dropped_columns PASSED                                                                                                                                                                                               [ 88%]
test_vcf.py::TestDataFrameActions::test_non_rename_columns_unaffacted PASSED                                                                                                                                                                                                    [ 94%]
test_vcf.py::TestDataFrameActions::test_renamed_correctly PASSED                                                                                                                                                                                                                [100%]

================================================================================================================================= 18 passed in 19.85s =================================================================================================================================
```

2022-04-21 21:30 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`resources/home/dnanexus/generate_workbook/tests/test_filters.py`](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py):

> [Line 140:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L140): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 173:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L173): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 191:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L191): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 211:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L211): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 232:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L232): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 259:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L259): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 286:9](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L286): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 288:17](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L288): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 289:21](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L289): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 297:56](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L297): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 298:47](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L298): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 299:65](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L299): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets

* In the file [`resources/home/dnanexus/generate_workbook/tests/test_vcf.py`](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_vcf.py):

> [Line 106:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L106): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 117:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L117): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)



* In the file [`resources/home/dnanexus/generate_workbook/utils/filters.py`](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/utils/filters.py):

> [Line 31:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/utils/filters.py#L31): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 80:5](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/utils/filters.py#L80): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 80:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/utils/filters.py#L80): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 97:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/utils/filters.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 98:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/utils/filters.py#L98): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)

* In the file [`resources/home/dnanexus/generate_workbook/utils/vcf.py`](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/utils/vcf.py):

> [Line 89:80](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/utils/vcf.py#L89): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

2022-04-22 12:10 UTC, mattgarner requested changes
> Reviewed 3 of 6 files at r1, 2 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/68)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[resources/home/dnanexus/generate_workbook/tests/test_filters.py, line 305 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/68#-N0G7o9z3RzBzDd39zLE:-N0G7o9z3RzBzDd39zLF:b-240gex) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L305)):*
> ```Python
>             "Filtering to exclude gnomAD_AF>0.01 and synonymous/intronic "
>             "variants filtered out the wrong variants"
>         )
> ```

Would it be a good idea to check that:
include count + exclude count = total count
include and exclude are mutually exclusive

This would ensure that everything we started with is in one of the two sets.

As it is, if include and/or exclude are missing variants then the check would still pass as long as the variants which are included meet the filter criteria

i.e. if we have a set of variants, and expected outcomes
```
A -> include
B -> include
C -> exclude
D -> exclude
```
If the actual result is:
```
included: A
excluded: C
missing: B,D
```
then the test passes.

Same would apply to the other similar filter tests - we're checking that the dfs contain variants which conform to the filter rules, but not checking if all variants are accounted for.



_Code quote:_
```Python
)
```


<!-- Sent from Reviewable.io -->

2022-04-22 12:17 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/68)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[resources/home/dnanexus/generate_workbook/tests/test_filters.py, line 305 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/68#-N0G7o9z3RzBzDd39zLE:-N0GBB2d27hIcoDDVg39:b-9y2pua) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L305)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Would it be a good idea to check that:
include count + exclude count = total count
include and exclude are mutually exclusive

This would ensure that everything we started with is in one of the two sets.

As it is, if include and/or exclude are missing variants then the check would still pass as long as the variants which are included meet the filter criteria

i.e. if we have a set of variants, and expected outcomes
```
A -> include
B -> include
C -> exclude
D -> exclude
```
If the actual result is:
```
included: A
excluded: C
missing: B,D
```
then the test passes.

Same would apply to the other similar filter tests - we're checking that the dfs contain variants which conform to the filter rules, but not checking if all variants are accounted for.
</blockquote></details>

I already have a check at run time for this: https://github.com/eastgenomics/eggd_generate_workbook/blob/d8488b05c329119bca9fd37b7bf895d69d940285/resources/home/dnanexus/generate_workbook/utils/filters.py#L187

Although I wasn't actually calling this in the test, so have added a call to it here in the filter tests as a sense check: https://github.com/eastgenomics/eggd_generate_workbook/blob/9ea0fce9554fae0b1d358101759b1aa9057bf6fe/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L189


<!-- Sent from Reviewable.io -->

2022-04-22 12:20 UTC, mattgarner approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/68)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

___
*[resources/home/dnanexus/generate_workbook/tests/test_filters.py, line 305 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/68#-N0G7o9z3RzBzDd39zLE:-N0GCovJ1S1XmMoXDltW:b-n8s3bp) ([raw file](https://github.com/eastgenomics/eggd_generate_workbook/blob/913fa3efaa76186b5ce2ff41fc783f29a18ea563/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L305)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I already have a check at run time for this: https://github.com/eastgenomics/eggd_generate_workbook/blob/d8488b05c329119bca9fd37b7bf895d69d940285/resources/home/dnanexus/generate_workbook/utils/filters.py#L187

Although I wasn't actually calling this in the test, so have added a call to it here in the filter tests as a sense check: https://github.com/eastgenomics/eggd_generate_workbook/blob/9ea0fce9554fae0b1d358101759b1aa9057bf6fe/resources/home/dnanexus/generate_workbook/tests/test_filters.py#L189
</blockquote></details>

Great, thanks :+1: 


<!-- Sent from Reviewable.io -->

2022-04-22 12:21 UTC, merged